apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  namespace: prometheus-monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 20 Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain